gear_array = [
    ["FASHION", "Pants", "20.00"],
    ["FASHION", "Top", "15.00"],
    ["FASHION", "Jacket", "35.00"],
    ["FASHION", "Footwear", "25.00"],
    ["FASHION", "Jewelry", "10-100.00"],
    ["FASHION", "Mirrorshades", "5-50.00"],
    ["FASHION", "Contact Lenses", "100.00"],
    ["FASHION", "Glasses", "50.00"],
    ["FASHION", "Generic Chic", "1 x cost"],
    ["FASHION", "Leisurewear", "2x cost"],
    ["FASHION", "Businesswear", "3x cost"],
    ["FASHION", "High Fashion", "4x cost"],
    ["FASHION", "Urban Flash", "2x cost"],
    ["TOOLS", "Techscanner", "600.00"],
    ["TOOLS", "Cutting torch", "40.00"],
    ["TOOLS", "Tech Toolkit", "100.00"],
    ["TOOLS", "B & ETools", "120.00"],
    ["TOOLS", "Electronics Toolkit", "100.00"],
    ["TOOLS", "Protective Goggles", "20.00"],
    ["TOOLS", "Flash tube", "2.00"],
    ["TOOLS", "Glowstik", "1.00"],
    ["TOOLS", "Flash Paint", "10.00 per pt."],
    ["TOOLS", "Flash Tape", "10.00 per foot"],
    ["TOOLS", "Rope", "2.00 per foot"],
    ["TOOLS", "Breathing Mask", "30.00"],
    ["PERSONAL ELECTRONICS", "Holo Generator", "500.00"],
    ["PERSONAL ELECTRONICS", "Video Board", "100.00 per sq ft"],
    ["PERSONAL ELECTRONICS", "Data Chip", "10.00"],
    ["PERSONAL ELECTRONICS", "Logcompass", "50.00"],
    ["PERSONAL ELECTRONICS", "Digital Recorder", "300.00"],
    ["PERSONAL ELECTRONICS", "Digital Camera", "150.00"],
    ["PERSONAL ELECTRONICS", "VideoCam", "800.00"],
    ["PERSONAL ELECTRONICS", "Video/Audio Tape Player", "40.00"],
    ["PERSONAL ELECTRONICS", "VideoTape", "4.00"],
    ["PERSONAL ELECTRONICS", "Pocket TV", "80.00"],
    ["PERSONAL ELECTRONICS", "Digital Chip Player", "150.00"],
    ["PERSONAL ELECTRONICS", "Digital Music Chip", "20.00"],
    ["PERSONAL ELECTRONICS", "Electric Guitar", "100-500.00"],
    ["PERSONAL ELECTRONICS", "Electronic Keyboard", "200-900.00"],
    ["PERSONAL ELECTRONICS", "Drum Synthesizer", "200-800.00"],
    ["PERSONAL ELECTRONICS", "Amplifier", "500-1000.00"],
    ["DATA SYSTEMS", "Laptop Computer", "900.00"],
    ["DATA SYSTEMS", "Pocket Computer", "100.00"],
    ["DATA SYSTEMS", "Cybermodem", "Varies by design"],
    ["DATA SYSTEMS", "Cellular Cybermodem", "Varies by design"],
    ["DATA SYSTEMS", "Interface Cables", "20-30.00"],
    ["DATA SYSTEMS", "Low Impedance cables", "60.00"],
    ["DATA SYSTEMS", "Trode Set", "20.00"],
    ["DATA SYSTEMS", "Keyboard", "100.00"],
    ["DATA SYSTEMS", "Terminal", "400.00"],
    ["COMMUNICATIONS", "Mastoid Commo", "100.00"],
    ["COMMUNICATIONS", "Pocket Commo", "50.00"],
    ["COMMUNICATIONS", "Cellular Phone", "400.00"],
    ["COMMUNICATIONS", "Mini Cell Phone", "800.00"],
    ["SURVEILLANCE", "Binoglasses", "200.00"],
    ["SURVEILLANCE", "Binoculars", "20.00"],
    ["SURVEILLANCE", "Light Booster Goggles", "200.00"],
    ["SURVEILLANCE", "IR Goggles", "250.00"],
    ["SURVEILLANCE", "IR Flash", "50.00"],
    ["ENTERTAINMENT", "Movie", "10.00"],
    ["ENTERTAINMENT", "VCR/Chip Rental", "4.00"],
    ["ENTERTAINMENT", "Braindance", "20.00"],
    ["ENTERTAINMENT", "Live Concert/Sports Event", "50.00"],
    ["ENTERTAINMENT", "Fast Food Meal", "5.00"],
    ["ENTERTAINMENT", "Well Drink", "3.00"],
    ["ENTERTAINMENT", "Restaurant Meal", "20.00"],
    ["ENTERTAINMENT", "Fair Restaurant", "1 x cost"],
    ["ENTERTAINMENT", "Good Restaurant", "2x cost"],
    ["ENTERTAINMENT", "Excellent Restaurant", "3x cost"],
    ["SECURITY", "Keylock", "20.00 per level"],
    ["SECURITY", "Cardlock", "100.00 per level"],
    ["SECURITY", "Vocolock", "200.00 per level"],
    ["SECURITY", "Line Tap", "200.00"],
    ["SECURITY", "CodeDecryptor", "500.00"],
    ["SECURITY", "VocDecryptor", "1000.00"],
    ["SECURITY", "Security Scanner", "1500.00"],
    ["SECURITY", "Poison Sniffer", "1500.00"],
    ["SECURITY", "Jamming Transmitter", "500.00"],
    ["SECURITY", "Scanner Plate", "500.00"],
    ["SECURITY", "Movement Sensor", "40.00"],
    ["SECURITY", "Passcard", "10.00"],
    ["SECURITY", "Tracking Device", "1000.00"],
    ["SECURITY", "Tracer Button", "50.00"],
    ["SECURITY", "Remote Sensors", "700.00"],
    ["SECURITY", "PlasKuffs", "100.00"],
    ["SECURITY", "Stripwire Binders", "5.00"],
    ["MEDICAL", "Dermal Stapler", "1000.00"],
    ["MEDICAL", "Spray Skin", "50.00 per can"],
    ["MEDICAL", "Slap Patch", "varies by drug type"],
    ["MEDICAL", "Cryotank", "100000.00"],
    ["MEDICAL", "Medkit", "50.00"],
    ["MEDICAL", "Surgical Kit", "400.00"],
    ["MEDICAL", "First Aid Kit", "10.00"],
    ["MEDICAL", "Medscanner", "300.00"],
    ["MEDICAL", "Drug Analyser", "75.00"],
    ["MEDICAL", "Airhypo", "100.00"],
    ["MEDICAL", "Clinic Visit", "200.00"],
    ["MEDICAL", "Day in Hospital", "300.00"],
    ["MEDICAL", "Day in Intensive Care", "1000.00"],
    ["MEDICAL", "Clone Limb Replacement", "1500.00"],
    ["FURNISHINGS", "Nylon Carrybag", "5.00"],
    ["FURNISHINGS", "Sleeping Bag", "25.00"],
    ["FURNISHINGS", "Inflatable Bed", "25.00"],
    ["FURNISHINGS", "Futon", "90.00"],
    ["FURNISHINGS", "Real Wood Furniture", "200.00 per piece"],
    ["FURNISHINGS", "Synthetic Furniture", "100.00 per piece"],
    ["FURNISHINGS", "Apartment Cube", "5000.00"],
    ["FURNISHINGS", "Lamp", "20.00"],
    ["FURNISHINGS", "Cleaning Bot", "1000.00"],
    ["FURNISHINGS", "Vocal Switcher System", "100.00"],
    ["VEHICLES", "Scooter", "500.00"],
    ["VEHICLES", "Motorcycle", "1500.00"],
    ["VEHICLES", "CityCar", "2000.00"],
    ["VEHICLES", "Small Subcompact", "6000.00"],
    ["VEHICLES", "Medium Sedan", "10000.00"],
    ["VEHICLES", "Sportscar", "20000.00"],
    ["VEHICLES", "Luxury Sedan", "40000.00"],
    ["VEHICLES", "Cybercontrols", "2x cost"],
    ["LIFESTYLE", "Cell Phone Service", "100.00 month +"],
    ["LIFESTYLE", "Standard Phone Service", "30.00 month +"],
    ["LIFESTYLE", "Pay Phone Call", "0.50 per minute"],
    ["LIFESTYLE", "Data Term Use", "1.00 per minute"],
    ["LIFESTYLE", "CredChip Account", "20.00 per month"],
    ["LIFESTYLE", "Health Plan", "1000.00 per month"],
    ["LIFESTYLE", "Trauma Team Acct.", "500.00 month"],
    ["LIFESTYLE", "Air", "5.00 per minute"],
    ["LIFESTYLE", "Mag Lev Chit", "0.25 per station"],
    ["LIFESTYLE", "Taxi", "3.00 per mile"],
    ["LIFESTYLE", "AV-Taxi", "10.00 per mile"],
    ["LIFESTYLE", "Cable TV", "40.00 per month"],
    ["GROCERIES", "Kibble", "50.00 per week"],
    ["GROCERIES", "Generic Prepak", "150.00 per week"],
    ["GROCERIES", "Good Prepak", "200.00 per week"],
    ["GROCERIES", "Fresh Food", "300.00 per week"],
    ["HOUSING", "Coffin", "20.00 per night"],
    ["HOUSING", "Hotel Room", "100 per night"],
    ["HOUSING", "Apt/Condo", "200.00 per room/per month"],
    ["HOUSING", "House", "150.00 per room/per month"],
    ["HOUSING", "Combat Zone", "1 x cost"],
    ["HOUSING", "Moderate Zone", "2x cost"],
    ["HOUSING", "Corporate Zone", "4x cost"],
    ["HOUSING", "Executive Zone", "6x cost"],
    ["HOUSING", "Utilities", "100.00 month"],
]
